file_read = open('file.txt', 'r')
print("File in Read Mode: ...")
print(file_read.read())
file_read.close()
file_write = open('file.txt', 'w')
file_write.write("File in write mode: ....")
print(file_write.write("HI I AM SARVESH "))
file_write.close()
file_append = open('file.txt', 'a')
file_append.write("File in append mode: ....")
print(file_append.write("HI I AM SARVESH "))
file_append.close()