file = open('Hi.txt', 'r')
print(file.read())
file.close()
file = open('Hi.txt', 'r')
print("\n Read in parts \n")
file.close()
file = open('Hi.txt', 'a')
file.close()
file = open('Hi.txt', 'a')
file.write('Amo')
file.close()
file = open('if.txt' , 'r')
print("Reading first line ....")
print(file.readline())
file.close()
file = open('if.txt' , 'r')
print("Reading multiple lins .......")
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file = open('if.txt', 'r')
print("Looping through the lines..")
for i in file:
    print(i)
file.close()