file_read = open('hi.txt', 'r')
print("File in read mode: .........")
print(file_read.read())
file_read.close()
file_write = open('hi.txt','w')
file_write.write("File in write mode: ...")
print(file_write.write("Hi i am batman"))
file_write.close()
file_append = open('hi.txt', 'a')
file_append.write("File in append mode: ......")
print(file_append.write("Yo i am joked"))
file_append.close()