file = open('Hay.txt' , 'r')
print("Reading first line ....")
print(file.readline())
file.close()
file = open('Hay.txt' , 'r')
print("Reading multiple lins .......")
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file = open('Hay.txt', 'r')
print("Looping through the lines..")
for i in file:
    print(i)
file.close()