file = open('Hi.txt', 'r')
print(file.read())
file.close()
file = open('Hi.txt', 'r')
print("\n Read in parts \n")
file.close()
file = open('Hi.txt', 'a')
file.close()
file = open('Hi.txt', 'a')
file.write('Amo')
file.close()